name: Changelog

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Releases.rst Updated
        run: |
          updated_files=$(git diff master..HEAD docs/source/releases.rst)
          if [[ -z $updated_files ]]
          then
            exit 1
          fi

      - name: Comment PR
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Please include the change for this PR in the changelog (`docs/source/releases.rst`).
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
